apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-api
spec:
  capacity:
    storage: 100Gi  # Adjust this based on your PVC request
  accessModes:
    - ReadWriteOnce  # Match this with your PVC accessModes
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default  # Ensure this matches the PVC's storageClassName
  hostPath:
    path: "/mnt/data"  # Adjust this based on your storage backend
